/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *nine;
  GtkWidget *seaven;
  GtkWidget *six;
  GtkWidget *five;
  GtkWidget *four;
  GtkWidget *three;
  GtkWidget *two;
  GtkWidget *one;
  GtkWidget *plus;
  GtkWidget *minus;
  GtkWidget *devide;
  GtkWidget *multiplication;
  GtkWidget *equal;
  GtkWidget *dot;
  GtkWidget *clear;
  GtkWidget *percent;
  GtkWidget *zero;
  GtkWidget *eight;
  GtkWidget *backspace;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 56, 16);
  gtk_widget_set_size_request (entry1, 288, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 16, 80);
  gtk_widget_set_size_request (nine, 70, 29);

  seaven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seaven);
  gtk_fixed_put (GTK_FIXED (fixed1), seaven, 184, 80);
  gtk_widget_set_size_request (seaven, 70, 29);

  six = gtk_button_new_from_stock ("6");
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 280, 80);
  gtk_widget_set_size_request (six, 69, 29);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 24, 128);
  gtk_widget_set_size_request (five, 70, 29);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 112, 128);
  gtk_widget_set_size_request (four, 70, 29);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 200, 128);
  gtk_widget_set_size_request (three, 70, 29);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 288, 128);
  gtk_widget_set_size_request (two, 69, 29);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 24, 168);
  gtk_widget_set_size_request (one, 70, 29);

  plus = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (plus);
  gtk_fixed_put (GTK_FIXED (fixed1), plus, 200, 168);
  gtk_widget_set_size_request (plus, 79, 29);

  minus = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (minus);
  gtk_fixed_put (GTK_FIXED (fixed1), minus, 288, 168);
  gtk_widget_set_size_request (minus, 78, 29);

  devide = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (devide);
  gtk_fixed_put (GTK_FIXED (fixed1), devide, 24, 208);
  gtk_widget_set_size_request (devide, 79, 29);

  multiplication = gtk_button_new_with_mnemonic (_("*"));
  gtk_widget_show (multiplication);
  gtk_fixed_put (GTK_FIXED (fixed1), multiplication, 112, 208);
  gtk_widget_set_size_request (multiplication, 78, 29);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 200, 208);
  gtk_widget_set_size_request (equal, 79, 29);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 296, 208);
  gtk_widget_set_size_request (dot, 79, 29);

  clear = gtk_button_new_with_mnemonic (_("clr"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 208, 256);
  gtk_widget_set_size_request (clear, 79, 29);

  percent = gtk_button_new_with_mnemonic (_("%"));
  gtk_widget_show (percent);
  gtk_fixed_put (GTK_FIXED (fixed1), percent, 24, 256);
  gtk_widget_set_size_request (percent, 79, 29);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 112, 168);
  gtk_widget_set_size_request (zero, 79, 29);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 96, 80);
  gtk_widget_set_size_request (eight, 69, 29);

  backspace = gtk_button_new_with_mnemonic (_("bsp"));
  gtk_widget_show (backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), backspace, 120, 256);
  gtk_widget_set_size_request (backspace, 78, 29);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) seaven, "clicked",
                    G_CALLBACK (on_seaven_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) plus, "clicked",
                    G_CALLBACK (on_plus_clicked),
                    NULL);
  g_signal_connect ((gpointer) minus, "clicked",
                    G_CALLBACK (on_minus_clicked),
                    NULL);
  g_signal_connect ((gpointer) devide, "clicked",
                    G_CALLBACK (on_devide_clicked),
                    NULL);
  g_signal_connect ((gpointer) multiplication, "clicked",
                    G_CALLBACK (on_multiplication_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) percent, "clicked",
                    G_CALLBACK (on_percent_clicked),
                    NULL);
  g_signal_connect ((gpointer) percent, "clicked",
                    G_CALLBACK (on_percent_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) backspace, "clicked",
                    G_CALLBACK (on_backspace_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, seaven, "seaven");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, plus, "plus");
  GLADE_HOOKUP_OBJECT (window1, minus, "minus");
  GLADE_HOOKUP_OBJECT (window1, devide, "devide");
  GLADE_HOOKUP_OBJECT (window1, multiplication, "multiplication");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, percent, "percent");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, backspace, "backspace");

  return window1;
}

